services:
  # ── 백엔드 (Spring Boot) ──
  # enviroment: db 매번 로컬이랑 도커랑 연결이 바꿔서 실행해야되서 환경변수로 설정
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: newnaeun-ncafe-backend
    ports:
      - "8032:8032"
    environment:
      - DB_URL=jdbc:postgresql://db:5432/ncafedb?useSSL=false&allowPublicKeyRetrieval=true
    volumes:
      - /home/newnaeun/dist/ncafe/upload:/app/upload
    restart: unless-stopped

  # ── 프론트엔드 (Next.js) ──
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: newnaeun-ncafe-frontend
    ports:
      - "3032:3032"
    environment:
      - BACKEND_URL=http://backend:8032
    depends_on:
      - backend
    restart: unless-stopped

  # ── 데이터베이스 (PostgreSQL) ──
  db:
    image: postgres:17
    profiles: [ "with-db" ]
    container_name: newnaeun-ncafe-db
    environment:
      POSTGRES_DB: ncafedb
      POSTGRES_USER: ncafe
      POSTGRES_PASSWORD: 1234
    ports:
      - "${DB_PORT:-5332}:5432"
    volumes:
      - ncafe-db-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  ncafe-db-data:
