# [DEV] Local Development Configuration
# 로컬 개발 시에는 SQL 로그를 상세히 보고, 로컬 DB에 접속합니다.

# DB 접속 정보 (기본 로컬 주소)
spring.datasource.url=jdbc:postgresql://localhost:5332/ncafedb?useSSL=false&allowPublicKeyRetrieval=true

# JPA 로그 상세 출력
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
